### Download the novel

In [36]:
import requests
url="https://gutenberg.org/cache/epub/73489/pg73489.txt"
response=requests.get(url)
if response.status_code == 200:
    with open("book.txt", "wb") as file:
        file.write(response.content)
else:
    print("File not found")

### Determine Start and End index of the text
#### Prepare an index_to_char and char_to_index dictionary that will come in handy later

In [20]:
with open("book.txt",'r',encoding="utf8") as fp:
    text=fp.read()
start_idx=text.index("Once upon a time there was a little girl named Anne Wilbraham")
end_idx=text.index("THE END")
text=text[start_idx:end_idx]
char_set=sorted(set(text))  ## Set function will prepare a list of unique characters in `text`
print(f"Total length of novel: {len(text)} \n")
print(f"Distinct characters: {char_set} \n")
print(f"Count of distinct characters: {len(char_set)} \n")

char_to_idx = { char:idx for idx,char  in enumerate(char_set) }
idx_to_char = { idx:char for (char,idx)  in char_to_idx.items() }

## Convert original text to integers
text_encoded = [ char_to_idx[char] for char in text ]
print(len(text_encoded))


print(idx_to_char)

Total length of novel: 192221 

Distinct characters: ['\n', ' ', '!', '(', ')', '*', '+', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '=', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '£', '½', 'é', '‘', '’', '“', '”'] 

Count of distinct characters: 86 

192221
{0: '\n', 1: ' ', 2: '!', 3: '(', 4: ')', 5: '*', 6: '+', 7: ',', 8: '-', 9: '.', 10: '0', 11: '1', 12: '2', 13: '3', 14: '4', 15: '5', 16: '6', 17: '7', 18: '8', 19: '9', 20: ':', 21: ';', 22: '=', 23: '?', 24: 'A', 25: 'B', 26: 'C', 27: 'D', 28: 'E', 29: 'F', 30: 'G', 31: 'H', 32: 'I', 33: 'J', 34: 'K', 35: 'L', 36: 'M', 37: 'N', 38: 'O', 39: 'P', 40: 'Q', 41: 'R', 42: 'S', 43: 'T', 44: 'U', 45: 'V', 46: 'W', 47: 'Y', 48: 'Z', 49: '[', 50: ']', 51: '_', 52: 'a', 53

### Prepare a custom dataset

In [106]:
# import torch
# from torch.utils.data import Dataset
# import numpy as np


# class PrepareData(Dataset):
#     def __init__(self,text_encoded, window_size=50):
#         self.text_encoded = text_encoded
#         self.window_size = window_size
#         self.input, self.label=self.getdata()

#     def __len__(self):
#         return len(self.input)

#     def __getitem__(self,idx):
#         input=self.input[idx]
#         label=self.label[idx]
#         return torch.tensor(input).long(), torch.tensor(label)

#     def getdata(self):
#         input=[]
#         label=[]
#         for i in range(len(self.text_encoded) - self.window_size):
#             input.append(self.text_encoded[i:i+self.window_size])
#             label.append(self.text_encoded[i+self.window_size])
#         return input,label

# window_size=200
# dataset=PrepareData(text_encoded, window_size=window_size)
# for i,j in dataset:
#     print(i.shape,j.shape)  ## 1 character output for every sequence of 50 letters(window_size)
#     print(i, "\n", j)
#     print("".join([idx_to_char[a.item()] for a in i]))   ##Print the first input(sequence)
#     print(idx_to_char[j.item()])  ##Print the first label, i.e next character prediction
#     break
# print(len(dataset))


torch.Size([200]) torch.Size([])
tensor([38, 65, 54, 56,  1, 72, 67, 66, 65,  1, 52,  1, 71, 60, 64, 56,  1, 71,
        59, 56, 69, 56,  1, 74, 52, 70,  1, 52,  1, 63, 60, 71, 71, 63, 56,  1,
        58, 60, 69, 63,  1, 65, 52, 64, 56, 55,  1, 24, 65, 65, 56,  1, 46, 60,
        63, 53, 69, 52, 59, 52, 64,  1, 25, 52, 76, 56, 70,  7,  0, 46, 60, 63,
        53, 69, 52, 59, 52, 64,  1, 53, 56, 60, 65, 58,  1, 52, 57, 71, 56, 69,
         1, 59, 56, 69,  1, 58, 69, 52, 65, 55, 57, 52, 71, 59, 56, 69,  1, 66,
        65,  1, 71, 59, 56,  1, 64, 66, 71, 59, 56, 69, 83, 70,  1, 70, 60, 55,
        56,  7,  1, 52,  1, 73, 56, 69, 76,  0, 54, 63, 56, 73, 56, 69,  1, 58,
        56, 65, 71, 63, 56, 64, 52, 65,  1, 63, 60, 73, 60, 65, 58,  1, 52, 71,
         1, 30, 69, 56, 52, 71,  1, 36, 52, 63, 73, 56, 69, 65,  7,  1, 52, 65,
        55,  1, 74, 69, 60, 71, 60, 65, 58,  1, 53, 66, 66, 62, 70,  1, 66, 65,
         1, 41]) 
 tensor(66)
Once upon a time there was a little girl named Anne Wilbr

In [182]:
## Trying to preare dataloaded in a different way
import torch
from torch.utils.data import Dataset
import numpy as np


class PrepareData(Dataset):
    def __init__(self,text_encoded, window_size=50):
        self.text_encoded = text_encoded
        self.window_size = window_size
        self.input, self.label=self.getdata()

    def __len__(self):
        return len(self.input)

    def __getitem__(self,idx):
        input=self.input[idx]
        label=self.label[idx]
        return torch.tensor(input).long(), torch.tensor(label)

    def getdata(self):
        input=[]
        label=[]
        for i in range(len(self.text_encoded) - self.window_size):
            input.append(self.text_encoded[i:i+self.window_size])
            label.append(self.text_encoded[i+1: i+self.window_size + 1])
        return input,label

window_size=50
dataset=PrepareData(text_encoded, window_size=window_size)
for i,j in dataset:
    print(i.shape, j.shape)
    print(i, "\n", j)
    print("".join([idx_to_char[a.item()] for a in i]))   ##Print the first input(sequence)
    print("".join([idx_to_char[b.item()] for b in j]))  ##Print the first label, i.e next character prediction
    break
print(len(dataset))


torch.Size([50]) torch.Size([50])
tensor([38, 65, 54, 56,  1, 72, 67, 66, 65,  1, 52,  1, 71, 60, 64, 56,  1, 71,
        59, 56, 69, 56,  1, 74, 52, 70,  1, 52,  1, 63, 60, 71, 71, 63, 56,  1,
        58, 60, 69, 63,  1, 65, 52, 64, 56, 55,  1, 24, 65, 65]) 
 tensor([65, 54, 56,  1, 72, 67, 66, 65,  1, 52,  1, 71, 60, 64, 56,  1, 71, 59,
        56, 69, 56,  1, 74, 52, 70,  1, 52,  1, 63, 60, 71, 71, 63, 56,  1, 58,
        60, 69, 63,  1, 65, 52, 64, 56, 55,  1, 24, 65, 65, 56])
Once upon a time there was a little girl named Ann
nce upon a time there was a little girl named Anne
192171


In [183]:
from torch.utils.data import DataLoader
batch_size = 32
torch.manual_seed(42)
seq_dl = DataLoader(dataset, batch_size=batch_size, shuffle=True, drop_last=True)
vocab_size = len(char_set)

i,l = next(iter(seq_dl))
print(i.shape)
print(l.shape)   ## 1 character output for every sequence

torch.Size([32, 50])
torch.Size([32, 50])


In [218]:
import torch.nn as nn
class RNN(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size,128) 
        self.lstm = nn.LSTM(128,256, num_layers=2, batch_first=True, dropout=0.5)  
        self.linear = nn.Linear(256,vocab_size)

    def forward(self,x, hidden=None):
        embedded=self.embedding(x)
        #print(embedded.shape)
        output, (h_n, c_n) = self.lstm(embedded)
        #print(output.shape)
        output = output[:, -1, :] ## We only want the last timestep
        #print(output.shape)
        output = self.linear(output)
        
        #output = self.linear(output) #.reshape(output.size(0), -1)
        return output,h_n
input,label=next(iter(seq_dl))
rnn=RNN(vocab_size)
print(rnn(input)[0].shape)  #output
print(rnn(input)[1].shape)  ## h_n

torch.Size([32, 86])
torch.Size([2, 32, 256])


In [ ]:
import random
import string
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(rnn.parameters(), lr=0.005)

rnn.train()
# Training loop
epochs=10000
for epoch in range(epochs):
    rnn.train()
    loss=0
    hidden=None
    inputs,labels=next(iter(seq_dl))  ### Pick a random batch
    #print(inputs.shape, labels.shape)
    #for inputs, labels in seq_dl:

    for i in range(window_size): 
        # Forward pass
        outputs,hidden = rnn(inputs[:,:i+1],hidden)

        # Calculate loss
        loss+=  criterion(outputs, labels[:,i])
    loss/=window_size

        # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    hidden=hidden.detach()


    # Print average loss for this epoch
    if epoch % 100 == 0:
        print(f"Epoch [{epoch}], Loss: {loss.item() :.4f}")
        seed=random.choice(string.ascii_letters) ## Get a random char
        generate_next_characters(rnn, seed, char_to_idx, idx_to_char,temperature=0.5)
        print("\n")
        

Epoch [0], Loss: 1.7255
Generated text:
and things and her bears of to her and the she was and the had the back the other and the time the rest the spunder was for the would rear a little be shoppend the and said the bang the time the but t


Epoch [100], Loss: 1.7766
Generated text:
peed and the come a got the seet a could the see more all sear was of the give have and the rest the get and in the half a latter and the somethers and Alison and so a long all the was of the keek and


Epoch [200], Loss: 1.6533
Generated text:
jother the tore the can I of was the took a boy there a like the was and so to but the put a looked sometherses with the cabelled a portambed a cold for and the tore and said the know broked a piught 




In [212]:
import numpy as np
from torch.distributions.categorical import Categorical
def generate_next_characters(model, seed, char_to_index, index_to_char, max_length=200, temperature=1.0):
    model.eval()  # Set the model to evaluation mode
    with torch.no_grad():
        # Convert the seed to tensor
        seed_tensor = torch.tensor([char_to_index[char] for char in seed], dtype=torch.long).unsqueeze(0)

        # Initialize the hidden state
        hidden = None

        # Generate next characters
        generated_text = seed
        for i in range(max_length):
            # Forward pass
            output, hidden = model(seed_tensor,hidden)

            # Sample the next character using temperature
            #probabilities = torch.softmax(output.squeeze() / temperature, dim=0)
            #next_index = torch.multinomial(probabilities, 1).item()
            #output=torch.softmax(output,dim=1)
            m = Categorical(logits=output/temperature)
            next_index = m.sample().item()

            # Convert the index to character
            next_char = index_to_char[next_index]

            # Append the next character to the generated text
            generated_text += next_char

            # Update the seed for the next iteration
            #seed_tensor=seed_tensor[:,1:]
            seed_tensor = torch.cat((seed_tensor,torch.tensor([[next_index]])), dim=1)
            
                    
            # Break if the generated text exceeds max length or if the next character is a newline
            #if next_char == '\n' or len(generated_text) >= max_length:
            if len(generated_text) >= max_length:
                break

    # Print the generated text
    print("Generated text:")
    print(generated_text)
    model.train()

seed = "I"
generate_next_characters(rnn, seed, char_to_idx, idx_to_char,temperature=0.5)


Generated text:
It was always longer, but the carriage was now about his news.

“Infirmary,” said Matilda.

“Oh, do doll’s have a new house were also on his coccass them indoors. Pembroke knew that
when he would do n
